package com.projectnight.configuration;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class ApplicationWebSecurityConfigurationInitializer extends AbstractSecurityWebApplicationInitializer {
}
