#
# Dockerfiles for authorization server (spring app), resource server (spring app) 
# and frontend server (angular app) are in their own folder. 
#

#
# For mysql database
#
FROM mysql:8.0.34
EXPOSE 3306
ADD projnightsqldump.sql /docker-entrypoint-initdb.d



